### ISSUE TITLE
Minus value of lat/lon doesn't work

### ISSUE THREAD

**Issue by tankaru** [mapcomparejp/JapanMapCompare#1]
If Japanese issue report is not acceptable, please let me know.

こんにちは。

JapanMapCompareをドラッグで移動して、例えばロンドンを表示すると普通に表示されます。
しかし、表示されたURLを新規タブで開こうとすると"No Page"となってしまいます。
例：https://mapcompare.jp/3/9/51.3545/-0.1771/osm/gRoad/mapSatellite

座標値がマイナスの場合に"No Page"となるようです。

**Comment by mapcomparejp** [comment]
こんにちは

JapanMapCompareについて、不具合部分のご指摘いただき大変ありがとうございます

先ほど修正を行い、表示できるようになりましたので、ご確認いただければと思います

(他の部分でも修正点などがあるため、githubには後ほど修正済みのファイルをアップロードします)

今後も、もし何か問題点などありましたら、日本語で構いませんのでご連絡いただければ幸いです

**Comment by tankaru** [comment]
修正していただき、どうもありがとうございます。
便利なツールなので活用させていただきます。
